name: Build & Deploy - Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_TUTOPROG }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_TUTOPROG }}

#   dont run this
on:
  push:
    branches:
      - main

jobs:
  Release:
    name: Deploy Production Build
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
 
      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Variables
        run: cd apps/tutorial && vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Build Project
        run: cd apps/tutorial && vercel build --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Deploy Project
        run: cd apps/tutorial && vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
